<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <Title>Umbraco Automate OpenIddict Core</Title>
        <Description>OAuth connection support for Umbraco Automate using OpenIddict Client WebIntegration</Description>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
        <StaticWebAssetBasePath>App_Plugins/UmbracoAutomateOpenIddict</StaticWebAssetBasePath>
        <!-- Required for Microsoft.AspNetCore.OpenApi source-generated interceptors (AddOpenApi) in v18. -->
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <PropertyGroup>
        <UseProjectReferences Condition="'$(UseProjectReferences)' == ''">true</UseProjectReferences>
    </PropertyGroup>

    <ItemGroup>
        <!-- Dont include the client folder as part of packaging nuget build -->
        <Content Remove="Client\**" />

        <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
        <None Include="Client\public\umbraco-package.json" Pack="false" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="OpenIddict.Client.WebIntegration" />
        <PackageReference Include="Umbraco.Cms.Persistence.EFCore" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\..\..\Umbraco.Automate\src\Umbraco.Automate.Core\Umbraco.Automate.Core.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
        <PackageReference Include="Umbraco.Automate.Core" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Umbraco.Automate.OpenIddict.Persistence.SqlServer</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Umbraco.Automate.OpenIddict.Persistence.Sqlite</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Umbraco.Automate.OpenIddict.Tests.Unit</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Umbraco.Automate.OpenIddict.Tests.Integration</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
