<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Umbraco Automate Persistence SQL Server</Title>
        <Description>SQL Server migrations for Umbraco Automate persistence</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
        <PackageReference Include="Umbraco.Cms.Persistence.EFCore.SqlServer" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Umbraco.Automate.Persistence\Umbraco.Automate.Persistence.csproj" />
    </ItemGroup>

</Project>
