<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Umbraco Automate Persistence</Title>
        <Description>EF Core persistence layer for Umbraco Automate</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetCore.CAP.SqlServer" />
        <PackageReference Include="DotNetCore.CAP.Sqlite" />
        <PackageReference Include="Umbraco.Cms.Persistence.EFCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Umbraco.Automate.Core\Umbraco.Automate.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Umbraco.Automate.Persistence.SqlServer</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Umbraco.Automate.Persistence.Sqlite</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Umbraco.Automate.Tests.Unit</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Umbraco.Automate.Tests.Integration</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
