// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAutomationsByIdData, DeleteAutomationsByIdErrors, DeleteAutomationsByIdResponses, DeleteConnectionsByIdData, DeleteConnectionsByIdErrors, DeleteConnectionsByIdResponses, DeleteWorkspacesByIdData, DeleteWorkspacesByIdErrors, DeleteWorkspacesByIdResponses, GetAutomationsByIdData, GetAutomationsByIdErrors, GetAutomationsByIdResponses, GetAutomationsByIdRunsData, GetAutomationsByIdRunsErrors, GetAutomationsByIdRunsResponses, GetAutomationsData, GetAutomationsErrors, GetAutomationsResponses, GetCatalogueActionsData, GetCatalogueActionsErrors, GetCatalogueActionsResponses, GetCatalogueConnectionTypesData, GetCatalogueConnectionTypesErrors, GetCatalogueConnectionTypesResponses, GetCatalogueTriggersData, GetCatalogueTriggersErrors, GetCatalogueTriggersResponses, GetConnectionsByIdData, GetConnectionsByIdErrors, GetConnectionsByIdResponses, GetConnectionsData, GetConnectionsErrors, GetConnectionsResponses, GetRunsByIdData, GetRunsByIdErrors, GetRunsByIdResponses, GetWorkspacesByIdData, GetWorkspacesByIdErrors, GetWorkspacesByIdResponses, GetWorkspacesData, GetWorkspacesErrors, GetWorkspacesResponses, PostAutomationsByIdPublishData, PostAutomationsByIdPublishErrors, PostAutomationsByIdPublishResponses, PostAutomationsByIdTriggerData, PostAutomationsByIdTriggerErrors, PostAutomationsByIdTriggerResponses, PostAutomationsByIdUnpublishData, PostAutomationsByIdUnpublishErrors, PostAutomationsByIdUnpublishResponses, PostAutomationsData, PostAutomationsErrors, PostAutomationsResponses, PostConnectionsData, PostConnectionsErrors, PostConnectionsResponses, PostWorkspacesData, PostWorkspacesErrors, PostWorkspacesResponses, PutAutomationsByIdData, PutAutomationsByIdErrors, PutAutomationsByIdResponses, PutConnectionsByIdData, PutConnectionsByIdErrors, PutConnectionsByIdResponses, PutWorkspacesByIdData, PutWorkspacesByIdErrors, PutWorkspacesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AutomationsService {
    public static getAutomations<ThrowOnError extends boolean = false>(options?: Options<GetAutomationsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAutomationsResponses, GetAutomationsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations',
            ...options
        });
    }
    
    public static postAutomations<ThrowOnError extends boolean = false>(options?: Options<PostAutomationsData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAutomationsResponses, PostAutomationsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteAutomationsById<ThrowOnError extends boolean = false>(options: Options<DeleteAutomationsByIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteAutomationsByIdResponses, DeleteAutomationsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}',
            ...options
        });
    }
    
    public static getAutomationsById<ThrowOnError extends boolean = false>(options: Options<GetAutomationsByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetAutomationsByIdResponses, GetAutomationsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}',
            ...options
        });
    }
    
    public static putAutomationsById<ThrowOnError extends boolean = false>(options: Options<PutAutomationsByIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutAutomationsByIdResponses, PutAutomationsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postAutomationsByIdPublish<ThrowOnError extends boolean = false>(options: Options<PostAutomationsByIdPublishData, ThrowOnError>) {
        return (options.client ?? client).post<PostAutomationsByIdPublishResponses, PostAutomationsByIdPublishErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}/publish',
            ...options
        });
    }
    
    public static getAutomationsByIdRuns<ThrowOnError extends boolean = false>(options: Options<GetAutomationsByIdRunsData, ThrowOnError>) {
        return (options.client ?? client).get<GetAutomationsByIdRunsResponses, GetAutomationsByIdRunsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}/runs',
            ...options
        });
    }
    
    public static postAutomationsByIdTrigger<ThrowOnError extends boolean = false>(options: Options<PostAutomationsByIdTriggerData, ThrowOnError>) {
        return (options.client ?? client).post<PostAutomationsByIdTriggerResponses, PostAutomationsByIdTriggerErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}/trigger',
            ...options
        });
    }
    
    public static postAutomationsByIdUnpublish<ThrowOnError extends boolean = false>(options: Options<PostAutomationsByIdUnpublishData, ThrowOnError>) {
        return (options.client ?? client).post<PostAutomationsByIdUnpublishResponses, PostAutomationsByIdUnpublishErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}/unpublish',
            ...options
        });
    }
}

export class CatalogueService {
    public static getCatalogueActions<ThrowOnError extends boolean = false>(options?: Options<GetCatalogueActionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCatalogueActionsResponses, GetCatalogueActionsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/catalogue/actions',
            ...options
        });
    }
    
    public static getCatalogueConnectionTypes<ThrowOnError extends boolean = false>(options?: Options<GetCatalogueConnectionTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCatalogueConnectionTypesResponses, GetCatalogueConnectionTypesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/catalogue/connection-types',
            ...options
        });
    }
    
    public static getCatalogueTriggers<ThrowOnError extends boolean = false>(options?: Options<GetCatalogueTriggersData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCatalogueTriggersResponses, GetCatalogueTriggersErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/catalogue/triggers',
            ...options
        });
    }
}

export class ConnectionsService {
    public static getConnections<ThrowOnError extends boolean = false>(options?: Options<GetConnectionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetConnectionsResponses, GetConnectionsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/connections',
            ...options
        });
    }
    
    public static postConnections<ThrowOnError extends boolean = false>(options?: Options<PostConnectionsData, ThrowOnError>) {
        return (options?.client ?? client).post<PostConnectionsResponses, PostConnectionsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/connections',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteConnectionsById<ThrowOnError extends boolean = false>(options: Options<DeleteConnectionsByIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteConnectionsByIdResponses, DeleteConnectionsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/connections/{id}',
            ...options
        });
    }
    
    public static getConnectionsById<ThrowOnError extends boolean = false>(options: Options<GetConnectionsByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetConnectionsByIdResponses, GetConnectionsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/connections/{id}',
            ...options
        });
    }
    
    public static putConnectionsById<ThrowOnError extends boolean = false>(options: Options<PutConnectionsByIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutConnectionsByIdResponses, PutConnectionsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/connections/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class RunsService {
    public static getRunsById<ThrowOnError extends boolean = false>(options: Options<GetRunsByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetRunsByIdResponses, GetRunsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/runs/{id}',
            ...options
        });
    }
}

export class WorkspacesService {
    public static getWorkspaces<ThrowOnError extends boolean = false>(options?: Options<GetWorkspacesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetWorkspacesResponses, GetWorkspacesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/workspaces',
            ...options
        });
    }
    
    public static postWorkspaces<ThrowOnError extends boolean = false>(options?: Options<PostWorkspacesData, ThrowOnError>) {
        return (options?.client ?? client).post<PostWorkspacesResponses, PostWorkspacesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/workspaces',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteWorkspacesById<ThrowOnError extends boolean = false>(options: Options<DeleteWorkspacesByIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteWorkspacesByIdResponses, DeleteWorkspacesByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/workspaces/{id}',
            ...options
        });
    }
    
    public static getWorkspacesById<ThrowOnError extends boolean = false>(options: Options<GetWorkspacesByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetWorkspacesByIdResponses, GetWorkspacesByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/workspaces/{id}',
            ...options
        });
    }
    
    public static putWorkspacesById<ThrowOnError extends boolean = false>(options: Options<PutWorkspacesByIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutWorkspacesByIdResponses, PutWorkspacesByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/workspaces/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
