// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAutomationsByIdData, DeleteAutomationsByIdErrors, DeleteAutomationsByIdResponses, GetAutomationsByIdData, GetAutomationsByIdErrors, GetAutomationsByIdResponses, GetAutomationsByIdRunsData, GetAutomationsByIdRunsErrors, GetAutomationsByIdRunsResponses, GetAutomationsData, GetAutomationsErrors, GetAutomationsResponses, GetCatalogueActionsData, GetCatalogueActionsErrors, GetCatalogueActionsResponses, GetCatalogueTriggersData, GetCatalogueTriggersErrors, GetCatalogueTriggersResponses, GetRunsByIdData, GetRunsByIdErrors, GetRunsByIdResponses, PostAutomationsByIdPublishData, PostAutomationsByIdPublishErrors, PostAutomationsByIdPublishResponses, PostAutomationsByIdTriggerData, PostAutomationsByIdTriggerErrors, PostAutomationsByIdTriggerResponses, PostAutomationsByIdUnpublishData, PostAutomationsByIdUnpublishErrors, PostAutomationsByIdUnpublishResponses, PostAutomationsData, PostAutomationsErrors, PostAutomationsResponses, PutAutomationsByIdData, PutAutomationsByIdErrors, PutAutomationsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AutomationsService {
    public static getAutomations<ThrowOnError extends boolean = false>(options?: Options<GetAutomationsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAutomationsResponses, GetAutomationsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations',
            ...options
        });
    }
    
    public static postAutomations<ThrowOnError extends boolean = false>(options?: Options<PostAutomationsData, ThrowOnError>) {
        return (options?.client ?? client).post<PostAutomationsResponses, PostAutomationsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteAutomationsById<ThrowOnError extends boolean = false>(options: Options<DeleteAutomationsByIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteAutomationsByIdResponses, DeleteAutomationsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}',
            ...options
        });
    }
    
    public static getAutomationsById<ThrowOnError extends boolean = false>(options: Options<GetAutomationsByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetAutomationsByIdResponses, GetAutomationsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}',
            ...options
        });
    }
    
    public static putAutomationsById<ThrowOnError extends boolean = false>(options: Options<PutAutomationsByIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutAutomationsByIdResponses, PutAutomationsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postAutomationsByIdPublish<ThrowOnError extends boolean = false>(options: Options<PostAutomationsByIdPublishData, ThrowOnError>) {
        return (options.client ?? client).post<PostAutomationsByIdPublishResponses, PostAutomationsByIdPublishErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}/publish',
            ...options
        });
    }
    
    public static getAutomationsByIdRuns<ThrowOnError extends boolean = false>(options: Options<GetAutomationsByIdRunsData, ThrowOnError>) {
        return (options.client ?? client).get<GetAutomationsByIdRunsResponses, GetAutomationsByIdRunsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}/runs',
            ...options
        });
    }
    
    public static postAutomationsByIdTrigger<ThrowOnError extends boolean = false>(options: Options<PostAutomationsByIdTriggerData, ThrowOnError>) {
        return (options.client ?? client).post<PostAutomationsByIdTriggerResponses, PostAutomationsByIdTriggerErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}/trigger',
            ...options
        });
    }
    
    public static postAutomationsByIdUnpublish<ThrowOnError extends boolean = false>(options: Options<PostAutomationsByIdUnpublishData, ThrowOnError>) {
        return (options.client ?? client).post<PostAutomationsByIdUnpublishResponses, PostAutomationsByIdUnpublishErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/automations/{id}/unpublish',
            ...options
        });
    }
}

export class CatalogueService {
    public static getCatalogueActions<ThrowOnError extends boolean = false>(options?: Options<GetCatalogueActionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCatalogueActionsResponses, GetCatalogueActionsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/catalogue/actions',
            ...options
        });
    }
    
    public static getCatalogueTriggers<ThrowOnError extends boolean = false>(options?: Options<GetCatalogueTriggersData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCatalogueTriggersResponses, GetCatalogueTriggersErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/catalogue/triggers',
            ...options
        });
    }
}

export class RunsService {
    public static getRunsById<ThrowOnError extends boolean = false>(options: Options<GetRunsByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetRunsByIdResponses, GetRunsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/automate/management/api/v1/runs/{id}',
            ...options
        });
    }
}
