// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44380' | (string & {});
};

export type ActionItemResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    group?: string | null;
    icon?: string | null;
    settingsSchema?: EditableModelSchemaResponseModel | null;
};

export type AutomationItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    isEnabled: boolean;
    workspaceId?: string | null;
    status: AutomationStatusModel;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type AutomationResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    isEnabled: boolean;
    status: AutomationStatusModel;
    publishedVersion?: number | null;
    workspaceId: string;
    trigger?: TriggerConfigurationModel | null;
    steps: Array<StepConfigurationModel>;
    connections: Array<StepConnectionModel>;
    canvasState?: string | null;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type AutomationRunResponseModel = {
    id: string;
    automationId: string;
    automationVersion: number;
    status: AutomationRunStatusModel;
    startedUtc?: string | null;
    completedUtc?: string | null;
    initiatedBy: string;
    correlationId?: string | null;
    error?: string | null;
    stepRuns: Array<StepRunResponseModel>;
};

export type AutomationRunStatusModel = 'Pending' | 'Running' | 'Completed' | 'Failed' | 'Suspended' | 'Cancelled';

export type AutomationStatusModel = 'Draft' | 'Published' | 'Inactive';

export type ConnectionItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    type: string;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type ConnectionResponseModel = {
    id: string;
    alias: string;
    name: string;
    type: string;
    settings: {
        [key: string]: unknown;
    };
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type ConnectionTypeItemResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    group?: string | null;
    icon?: string | null;
    settingsSchema?: EditableModelSchemaResponseModel | null;
};

export type CreateAutomationRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    workspaceId: string;
    isEnabled: boolean;
    trigger?: TriggerConfigurationModel | null;
    steps: Array<StepConfigurationModel>;
    connections: Array<StepConnectionModel>;
    canvasState?: string | null;
};

export type CreateConnectionRequestModel = {
    alias: string;
    name: string;
    type: string;
    settings: {
        [key: string]: unknown;
    };
};

export type CreateWorkspaceRequestModel = {
    alias: string;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
    allowedConnections: Array<string>;
};

export type EditableModelFieldDescriptorResponseModel = {
    propertyName: string;
    label: string;
    propertyType: string;
    description?: string | null;
    editorUiAlias?: string | null;
    editorConfig?: string | null;
    sortOrder: number;
    isSensitive: boolean;
    group?: string | null;
    isRequired: boolean;
};

export type EditableModelSchemaResponseModel = {
    fields: Array<EditableModelFieldDescriptorResponseModel>;
};

export type PagedAutomationItemResponseModel = {
    total: number;
    items: Array<AutomationItemResponseModel>;
};

export type PagedAutomationRunResponseModel = {
    total: number;
    items: Array<AutomationRunResponseModel>;
};

export type PagedConnectionItemResponseModel = {
    total: number;
    items: Array<ConnectionItemResponseModel>;
};

export type PagedWorkspaceItemResponseModel = {
    total: number;
    items: Array<WorkspaceItemResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type StepConfigurationModel = {
    id: string;
    actionAlias: string;
    name: string;
    connectionId?: string | null;
    settings: {
        [key: string]: unknown;
    };
    inputMappings: {
        [key: string]: string;
    };
    position: StepPositionModel;
    errorBehavior: StepErrorBehaviorModel;
    retryInterval?: string | null;
    maxRetries?: number | null;
};

export type StepConnectionModel = {
    sourceStepId: string;
    sourceHandle?: string | null;
    targetStepId: string;
    targetHandle?: string | null;
    outcome?: string | null;
};

export type StepErrorBehaviorModel = 'Retry' | 'Suspend' | 'Terminate' | 'Compensate';

export type StepPositionModel = {
    x: number;
    y: number;
};

export type StepRunResponseModel = {
    id: string;
    stepId: string;
    actionAlias: string;
    status: StepRunStatusModel;
    startedUtc?: string | null;
    completedUtc?: string | null;
    error?: string | null;
    retryCount: number;
    durationMs?: number | null;
};

export type StepRunStatusModel = 'Pending' | 'Running' | 'Completed' | 'Failed' | 'Skipped' | 'WaitingForInput';

export type TriggerConfigurationModel = {
    triggerAlias: string;
    settings: {
        [key: string]: unknown;
    };
};

export type TriggerItemResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    group?: string | null;
    icon?: string | null;
    settingsSchema?: EditableModelSchemaResponseModel | null;
    outputProperties: Array<TriggerOutputPropertyResponseModel>;
};

export type TriggerOutputPropertyResponseModel = {
    name: string;
    type: string;
    description?: string | null;
};

export type UpdateAutomationRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    isEnabled: boolean;
    trigger?: TriggerConfigurationModel | null;
    steps: Array<StepConfigurationModel>;
    connections: Array<StepConnectionModel>;
    canvasState?: string | null;
};

export type UpdateConnectionRequestModel = {
    alias: string;
    name: string;
    type: string;
    settings: {
        [key: string]: unknown;
    };
};

export type UpdateWorkspaceRequestModel = {
    alias: string;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
    allowedConnections: Array<string>;
};

export type WorkspaceItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    serviceAccountKey: string;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type WorkspaceResponseModel = {
    id: string;
    alias: string;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
    allowedConnections: Array<string>;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type GetAutomationsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/automations';
};

export type GetAutomationsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAutomationsResponses = {
    /**
     * OK
     */
    200: PagedAutomationItemResponseModel;
};

export type GetAutomationsResponse = GetAutomationsResponses[keyof GetAutomationsResponses];

export type PostAutomationsData = {
    body?: CreateAutomationRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations';
};

export type PostAutomationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostAutomationsError = PostAutomationsErrors[keyof PostAutomationsErrors];

export type PostAutomationsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteAutomationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type DeleteAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAutomationsByIdError = DeleteAutomationsByIdErrors[keyof DeleteAutomationsByIdErrors];

export type DeleteAutomationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type GetAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdError = GetAutomationsByIdErrors[keyof GetAutomationsByIdErrors];

export type GetAutomationsByIdResponses = {
    /**
     * OK
     */
    200: AutomationResponseModel;
};

export type GetAutomationsByIdResponse = GetAutomationsByIdResponses[keyof GetAutomationsByIdResponses];

export type PutAutomationsByIdData = {
    body?: UpdateAutomationRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type PutAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutAutomationsByIdError = PutAutomationsByIdErrors[keyof PutAutomationsByIdErrors];

export type PutAutomationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAutomationsByIdPublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/publish';
};

export type PostAutomationsByIdPublishErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
};

export type PostAutomationsByIdPublishError = PostAutomationsByIdPublishErrors[keyof PostAutomationsByIdPublishErrors];

export type PostAutomationsByIdPublishResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsByIdRunsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/automations/{id}/runs';
};

export type GetAutomationsByIdRunsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdRunsError = GetAutomationsByIdRunsErrors[keyof GetAutomationsByIdRunsErrors];

export type GetAutomationsByIdRunsResponses = {
    /**
     * OK
     */
    200: PagedAutomationRunResponseModel;
};

export type GetAutomationsByIdRunsResponse = GetAutomationsByIdRunsResponses[keyof GetAutomationsByIdRunsResponses];

export type PostAutomationsByIdTriggerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/trigger';
};

export type PostAutomationsByIdTriggerErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostAutomationsByIdTriggerError = PostAutomationsByIdTriggerErrors[keyof PostAutomationsByIdTriggerErrors];

export type PostAutomationsByIdTriggerResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PostAutomationsByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/unpublish';
};

export type PostAutomationsByIdUnpublishErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostAutomationsByIdUnpublishError = PostAutomationsByIdUnpublishErrors[keyof PostAutomationsByIdUnpublishErrors];

export type PostAutomationsByIdUnpublishResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCatalogueActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/actions';
};

export type GetCatalogueActionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueActionsResponses = {
    /**
     * OK
     */
    200: Array<ActionItemResponseModel>;
};

export type GetCatalogueActionsResponse = GetCatalogueActionsResponses[keyof GetCatalogueActionsResponses];

export type GetCatalogueConnectionTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/connection-types';
};

export type GetCatalogueConnectionTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueConnectionTypesResponses = {
    /**
     * OK
     */
    200: Array<ConnectionTypeItemResponseModel>;
};

export type GetCatalogueConnectionTypesResponse = GetCatalogueConnectionTypesResponses[keyof GetCatalogueConnectionTypesResponses];

export type GetCatalogueTriggersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/triggers';
};

export type GetCatalogueTriggersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueTriggersResponses = {
    /**
     * OK
     */
    200: Array<TriggerItemResponseModel>;
};

export type GetCatalogueTriggersResponse = GetCatalogueTriggersResponses[keyof GetCatalogueTriggersResponses];

export type GetConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/connections';
};

export type GetConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConnectionsResponses = {
    /**
     * OK
     */
    200: PagedConnectionItemResponseModel;
};

export type GetConnectionsResponse = GetConnectionsResponses[keyof GetConnectionsResponses];

export type PostConnectionsData = {
    body?: CreateConnectionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections';
};

export type PostConnectionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostConnectionsError = PostConnectionsErrors[keyof PostConnectionsErrors];

export type PostConnectionsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteConnectionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type DeleteConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteConnectionsByIdError = DeleteConnectionsByIdErrors[keyof DeleteConnectionsByIdErrors];

export type DeleteConnectionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type GetConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConnectionsByIdError = GetConnectionsByIdErrors[keyof GetConnectionsByIdErrors];

export type GetConnectionsByIdResponses = {
    /**
     * OK
     */
    200: ConnectionResponseModel;
};

export type GetConnectionsByIdResponse = GetConnectionsByIdResponses[keyof GetConnectionsByIdResponses];

export type PutConnectionsByIdData = {
    body?: UpdateConnectionRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type PutConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutConnectionsByIdError = PutConnectionsByIdErrors[keyof PutConnectionsByIdErrors];

export type PutConnectionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/runs/{id}';
};

export type GetRunsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetRunsByIdError = GetRunsByIdErrors[keyof GetRunsByIdErrors];

export type GetRunsByIdResponses = {
    /**
     * OK
     */
    200: AutomationRunResponseModel;
};

export type GetRunsByIdResponse = GetRunsByIdResponses[keyof GetRunsByIdResponses];

export type GetWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/workspaces';
};

export type GetWorkspacesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetWorkspacesResponses = {
    /**
     * OK
     */
    200: PagedWorkspaceItemResponseModel;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type PostWorkspacesData = {
    body?: CreateWorkspaceRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces';
};

export type PostWorkspacesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostWorkspacesError = PostWorkspacesErrors[keyof PostWorkspacesErrors];

export type PostWorkspacesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type DeleteWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteWorkspacesByIdError = DeleteWorkspacesByIdErrors[keyof DeleteWorkspacesByIdErrors];

export type DeleteWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type GetWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetWorkspacesByIdError = GetWorkspacesByIdErrors[keyof GetWorkspacesByIdErrors];

export type GetWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: WorkspaceResponseModel;
};

export type GetWorkspacesByIdResponse = GetWorkspacesByIdResponses[keyof GetWorkspacesByIdResponses];

export type PutWorkspacesByIdData = {
    body?: UpdateWorkspaceRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type PutWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutWorkspacesByIdError = PutWorkspacesByIdErrors[keyof PutWorkspacesByIdErrors];

export type PutWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
