// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44380' | (string & {});
};

export type ActionItemResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    group?: string | null;
    icon?: string | null;
    settingsSchema?: EditableModelSchemaModel | null;
};

export type ApprovalDecisionRequestModel = {
    outcome: ApprovalOutcomeModel;
    comment?: string | null;
};

export type ApprovalOutcomeModel = 'Approved' | 'Rejected';

export type AutomationAncestorResponseModel = {
    id: string;
    entityType: string;
    name: string;
    parentId?: string | null;
    parentEntityType?: string | null;
    hasChildren: boolean;
    isFolder: boolean;
};

export type AutomationItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    isEnabled: boolean;
    workspaceId: string;
    groupId?: string | null;
    status: AutomationStatusModel;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type AutomationNotificationSettingsModel = {
    notifyOn: NotifyOnModel;
    channels: Array<ChannelConfigurationModel>;
};

export type AutomationResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    isEnabled: boolean;
    status: AutomationStatusModel;
    publishedVersion?: number | null;
    workspaceId: string;
    groupId?: string | null;
    trigger?: TriggerConfigurationModel | null;
    steps: Array<StepConfigurationModel>;
    connections: Array<StepConnectionModel>;
    canvasState?: string | null;
    version: number;
    dateCreated: string;
    dateModified: string;
    notificationSettings?: AutomationNotificationSettingsModel | null;
};

export type AutomationRunCountModel = {
    automationId: string;
    automationName: string;
    totalRuns: number;
    successCount: number;
    failCount: number;
};

export type AutomationRunResponseModel = {
    id: string;
    automationId: string;
    automationVersion: number;
    status: AutomationRunStatusModel;
    startedUtc?: string | null;
    completedUtc?: string | null;
    initiatedBy: string;
    correlationId?: string | null;
    error?: string | null;
    stepRuns: Array<StepRunResponseModel>;
};

export type AutomationRunStatusModel = 'Pending' | 'Running' | 'Completed' | 'Failed' | 'Suspended' | 'Cancelled';

export type AutomationStatusModel = 'Draft' | 'Published' | 'Inactive';

export type ChannelConfigurationModel = {
    channelAlias: string;
    settings: {
        [key: string]: unknown;
    };
    isEnabled: boolean;
};

export type ConnectionItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    type: string;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type ConnectionResponseModel = {
    id: string;
    alias: string;
    name: string;
    type: string;
    settings: {
        [key: string]: unknown;
    };
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type ConnectionTypeItemResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    group?: string | null;
    icon?: string | null;
    settingsSchema?: EditableModelSchemaModel | null;
};

export type CreateAutomationRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    workspaceId: string;
    isEnabled: boolean;
    groupId?: string | null;
    trigger?: TriggerConfigurationModel | null;
    steps: Array<StepConfigurationModel>;
    connections: Array<StepConnectionModel>;
    canvasState?: string | null;
    notificationSettings?: AutomationNotificationSettingsModel | null;
};

export type CreateConnectionRequestModel = {
    alias: string;
    name: string;
    type: string;
    settings: {
        [key: string]: unknown;
    };
};

export type CreateWorkspaceGroupRequestModel = {
    name: string;
    parentId?: string | null;
};

export type CreateWorkspaceRequestModel = {
    alias: string;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
    allowedConnections: Array<string>;
};

export type EditableModelFieldDescriptorModel = {
    key: string;
    label: string;
    description?: string | null;
    editorUiAlias?: string | null;
    editorConfig?: string | null;
    defaultValue?: unknown;
    sortOrder: number;
    isSensitive: boolean;
    isRequired: boolean;
    group?: string | null;
    supportsExpressions: boolean;
};

export type EditableModelSchemaModel = {
    type?: string | null;
    fields: Array<EditableModelFieldDescriptorModel>;
};

export type EntityVersionComparisonResponseModel = {
    fromVersion: number;
    toVersion: number;
    changes: Array<ValueChangeModel>;
};

export type EntityVersionHistoryResponseModel = {
    currentVersion: number;
    totalVersions: number;
    publishedVersion?: number | null;
    versions: Array<EntityVersionResponseModel>;
};

export type EntityVersionResponseModel = {
    id: string;
    entityId: string;
    version: number;
    dateCreated: string;
    createdByUserId?: string | null;
    changeDescription?: string | null;
    isPublished: boolean;
};

export type NotificationChannelItemResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    icon?: string | null;
    settingsSchema?: EditableModelSchemaModel | null;
};

export type NotifyOnModel = 'Never' | 'Failed' | 'Suspended' | 'FailedOrSuspended' | 'Completed' | 'Recovered';

export type PagedAutomationItemResponseModel = {
    total: number;
    items: Array<AutomationItemResponseModel>;
};

export type PagedAutomationRunResponseModel = {
    total: number;
    items: Array<AutomationRunResponseModel>;
};

export type PagedConnectionItemResponseModel = {
    total: number;
    items: Array<ConnectionItemResponseModel>;
};

export type PagedWorkspaceItemResponseModel = {
    total: number;
    items: Array<WorkspaceItemResponseModel>;
};

export type PendingApprovalResponseModel = {
    runId: string;
    stepId: string;
    automationId: string;
    automationName: string;
    prompt?: string | null;
    requestedUtc?: string | null;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type RunSummaryModel = {
    totalRuns: number;
    byStatus: {
        Pending: number;
        Running: number;
        Completed: number;
        Failed: number;
        Suspended: number;
        Cancelled: number;
    };
    successRate: number;
};

export type StepConfigurationModel = {
    id: string;
    actionAlias: string;
    name: string;
    connectionId?: string | null;
    settings: {
        [key: string]: unknown;
    };
    inputMappings: {
        [key: string]: string;
    };
    position: StepPositionModel;
    errorBehavior: StepErrorBehaviorModel;
    retryInterval?: string | null;
    maxRetries?: number | null;
};

export type StepConnectionModel = {
    sourceStepId: string;
    sourceHandle?: string | null;
    targetStepId: string;
    targetHandle?: string | null;
    outcome?: string | null;
};

export type StepErrorBehaviorModel = 'Retry' | 'Suspend' | 'Terminate' | 'Compensate';

export type StepPositionModel = {
    x: number;
    y: number;
};

export type StepRunResponseModel = {
    id: string;
    stepId: string;
    actionAlias: string;
    status: StepRunStatusModel;
    startedUtc?: string | null;
    completedUtc?: string | null;
    error?: string | null;
    retryCount: number;
    durationMs?: number | null;
};

export type StepRunStatusModel = 'Pending' | 'Running' | 'Completed' | 'Failed' | 'Skipped' | 'WaitingForInput';

export type TriggerConfigurationModel = {
    triggerAlias: string;
    settings: {
        [key: string]: unknown;
    };
};

export type TriggerItemResponseModel = {
    alias: string;
    name: string;
    description?: string | null;
    group?: string | null;
    icon?: string | null;
    settingsSchema?: EditableModelSchemaModel | null;
    outputProperties: Array<TriggerOutputPropertyModel>;
};

export type TriggerOutputPropertyModel = {
    name: string;
    type: string;
    description?: string | null;
};

export type UpdateAutomationRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    isEnabled: boolean;
    groupId?: string | null;
    trigger?: TriggerConfigurationModel | null;
    steps: Array<StepConfigurationModel>;
    connections: Array<StepConnectionModel>;
    canvasState?: string | null;
    notificationSettings?: AutomationNotificationSettingsModel | null;
};

export type UpdateConnectionRequestModel = {
    alias: string;
    name: string;
    type: string;
    settings: {
        [key: string]: unknown;
    };
};

export type UpdateWorkspaceGroupRequestModel = {
    name: string;
    parentId?: string | null;
};

export type UpdateWorkspaceRequestModel = {
    alias: string;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
    allowedConnections: Array<string>;
};

export type ValueChangeModel = {
    path: string;
    oldValue?: string | null;
    newValue?: string | null;
};

export type WorkspaceGroupResponseModel = {
    id: string;
    name: string;
    parentId?: string | null;
    dateCreated: string;
};

export type WorkspaceItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    serviceAccountKey: string;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type WorkspaceResponseModel = {
    id: string;
    alias: string;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
    allowedConnections: Array<string>;
    version: number;
    dateCreated: string;
    dateModified: string;
};

export type PostApprovalsByRunIdStepsByStepIdDecisionData = {
    body?: ApprovalDecisionRequestModel;
    path: {
        runId: string;
        stepId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/approvals/{runId}/steps/{stepId}/decision';
};

export type PostApprovalsByRunIdStepsByStepIdDecisionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostApprovalsByRunIdStepsByStepIdDecisionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApprovalsPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/approvals/pending';
};

export type GetApprovalsPendingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetApprovalsPendingResponses = {
    /**
     * OK
     */
    200: Array<PendingApprovalResponseModel>;
};

export type GetApprovalsPendingResponse = GetApprovalsPendingResponses[keyof GetApprovalsPendingResponses];

export type GetAutomationsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        groupId?: string;
        workspaceId?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/automations';
};

export type GetAutomationsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAutomationsResponses = {
    /**
     * OK
     */
    200: PagedAutomationItemResponseModel;
};

export type GetAutomationsResponse = GetAutomationsResponses[keyof GetAutomationsResponses];

export type PostAutomationsData = {
    body?: CreateAutomationRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations';
};

export type PostAutomationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostAutomationsError = PostAutomationsErrors[keyof PostAutomationsErrors];

export type PostAutomationsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteAutomationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type DeleteAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAutomationsByIdError = DeleteAutomationsByIdErrors[keyof DeleteAutomationsByIdErrors];

export type DeleteAutomationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type GetAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdError = GetAutomationsByIdErrors[keyof GetAutomationsByIdErrors];

export type GetAutomationsByIdResponses = {
    /**
     * OK
     */
    200: AutomationResponseModel;
};

export type GetAutomationsByIdResponse = GetAutomationsByIdResponses[keyof GetAutomationsByIdResponses];

export type PutAutomationsByIdData = {
    body?: UpdateAutomationRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type PutAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutAutomationsByIdError = PutAutomationsByIdErrors[keyof PutAutomationsByIdErrors];

export type PutAutomationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsByIdAncestorsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/ancestors';
};

export type GetAutomationsByIdAncestorsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdAncestorsError = GetAutomationsByIdAncestorsErrors[keyof GetAutomationsByIdAncestorsErrors];

export type GetAutomationsByIdAncestorsResponses = {
    /**
     * OK
     */
    200: Array<AutomationAncestorResponseModel>;
};

export type GetAutomationsByIdAncestorsResponse = GetAutomationsByIdAncestorsResponses[keyof GetAutomationsByIdAncestorsResponses];

export type PostAutomationsByIdPublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/publish';
};

export type PostAutomationsByIdPublishErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ProblemDetails;
};

export type PostAutomationsByIdPublishError = PostAutomationsByIdPublishErrors[keyof PostAutomationsByIdPublishErrors];

export type PostAutomationsByIdPublishResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsByIdRunsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/automations/{id}/runs';
};

export type GetAutomationsByIdRunsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdRunsError = GetAutomationsByIdRunsErrors[keyof GetAutomationsByIdRunsErrors];

export type GetAutomationsByIdRunsResponses = {
    /**
     * OK
     */
    200: PagedAutomationRunResponseModel;
};

export type GetAutomationsByIdRunsResponse = GetAutomationsByIdRunsResponses[keyof GetAutomationsByIdRunsResponses];

export type PostAutomationsByIdTriggerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/trigger';
};

export type PostAutomationsByIdTriggerErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostAutomationsByIdTriggerError = PostAutomationsByIdTriggerErrors[keyof PostAutomationsByIdTriggerErrors];

export type PostAutomationsByIdTriggerResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PostAutomationsByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/unpublish';
};

export type PostAutomationsByIdUnpublishErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostAutomationsByIdUnpublishError = PostAutomationsByIdUnpublishErrors[keyof PostAutomationsByIdUnpublishErrors];

export type PostAutomationsByIdUnpublishResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCatalogueActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/actions';
};

export type GetCatalogueActionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueActionsResponses = {
    /**
     * OK
     */
    200: Array<ActionItemResponseModel>;
};

export type GetCatalogueActionsResponse = GetCatalogueActionsResponses[keyof GetCatalogueActionsResponses];

export type GetCatalogueConnectionTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/connection-types';
};

export type GetCatalogueConnectionTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueConnectionTypesResponses = {
    /**
     * OK
     */
    200: Array<ConnectionTypeItemResponseModel>;
};

export type GetCatalogueConnectionTypesResponse = GetCatalogueConnectionTypesResponses[keyof GetCatalogueConnectionTypesResponses];

export type GetCatalogueNotificationChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/notification-channels';
};

export type GetCatalogueNotificationChannelsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueNotificationChannelsResponses = {
    /**
     * OK
     */
    200: Array<NotificationChannelItemResponseModel>;
};

export type GetCatalogueNotificationChannelsResponse = GetCatalogueNotificationChannelsResponses[keyof GetCatalogueNotificationChannelsResponses];

export type GetCatalogueTriggersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/triggers';
};

export type GetCatalogueTriggersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueTriggersResponses = {
    /**
     * OK
     */
    200: Array<TriggerItemResponseModel>;
};

export type GetCatalogueTriggersResponse = GetCatalogueTriggersResponses[keyof GetCatalogueTriggersResponses];

export type GetConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/connections';
};

export type GetConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConnectionsResponses = {
    /**
     * OK
     */
    200: PagedConnectionItemResponseModel;
};

export type GetConnectionsResponse = GetConnectionsResponses[keyof GetConnectionsResponses];

export type PostConnectionsData = {
    body?: CreateConnectionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections';
};

export type PostConnectionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostConnectionsError = PostConnectionsErrors[keyof PostConnectionsErrors];

export type PostConnectionsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteConnectionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type DeleteConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteConnectionsByIdError = DeleteConnectionsByIdErrors[keyof DeleteConnectionsByIdErrors];

export type DeleteConnectionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type GetConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConnectionsByIdError = GetConnectionsByIdErrors[keyof GetConnectionsByIdErrors];

export type GetConnectionsByIdResponses = {
    /**
     * OK
     */
    200: ConnectionResponseModel;
};

export type GetConnectionsByIdResponse = GetConnectionsByIdResponses[keyof GetConnectionsByIdResponses];

export type PutConnectionsByIdData = {
    body?: UpdateConnectionRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type PutConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutConnectionsByIdError = PutConnectionsByIdErrors[keyof PutConnectionsByIdErrors];

export type PutConnectionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetMetricsData = {
    body?: never;
    path?: never;
    query?: {
        workspaceId?: string;
        from?: string;
        to?: string;
    };
    url: '/umbraco/automate/management/api/v1/metrics';
};

export type GetMetricsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetMetricsResponses = {
    /**
     * OK
     */
    200: RunSummaryModel;
};

export type GetMetricsResponse = GetMetricsResponses[keyof GetMetricsResponses];

export type GetMetricsByAutomationData = {
    body?: never;
    path?: never;
    query?: {
        workspaceId?: string;
        from?: string;
        to?: string;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/metrics/by-automation';
};

export type GetMetricsByAutomationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetMetricsByAutomationResponses = {
    /**
     * OK
     */
    200: Array<AutomationRunCountModel>;
};

export type GetMetricsByAutomationResponse = GetMetricsByAutomationResponses[keyof GetMetricsByAutomationResponses];

export type GetRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/runs/{id}';
};

export type GetRunsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetRunsByIdError = GetRunsByIdErrors[keyof GetRunsByIdErrors];

export type GetRunsByIdResponses = {
    /**
     * OK
     */
    200: AutomationRunResponseModel;
};

export type GetRunsByIdResponse = GetRunsByIdResponses[keyof GetRunsByIdResponses];

export type GetVersionHistoryByEntityTypeByEntityIdData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/version-history/{entityType}/{entityId}';
};

export type GetVersionHistoryByEntityTypeByEntityIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionHistoryByEntityTypeByEntityIdError = GetVersionHistoryByEntityTypeByEntityIdErrors[keyof GetVersionHistoryByEntityTypeByEntityIdErrors];

export type GetVersionHistoryByEntityTypeByEntityIdResponses = {
    /**
     * OK
     */
    200: EntityVersionHistoryResponseModel;
};

export type GetVersionHistoryByEntityTypeByEntityIdResponse = GetVersionHistoryByEntityTypeByEntityIdResponses[keyof GetVersionHistoryByEntityTypeByEntityIdResponses];

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        entityVersion: number;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/version-history/{entityType}/{entityId}/{entityVersion}';
};

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionError = GetVersionHistoryByEntityTypeByEntityIdByEntityVersionErrors[keyof GetVersionHistoryByEntityTypeByEntityIdByEntityVersionErrors];

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionResponses = {
    /**
     * OK
     */
    200: EntityVersionResponseModel;
};

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionResponse = GetVersionHistoryByEntityTypeByEntityIdByEntityVersionResponses[keyof GetVersionHistoryByEntityTypeByEntityIdByEntityVersionResponses];

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        entityVersion: number;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/version-history/{entityType}/{entityId}/{entityVersion}/rollback';
};

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackError = PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackErrors[keyof PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackErrors];

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackResponse = PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackResponses[keyof PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackResponses];

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        fromEntityVersion: number;
        toEntityVersion: number;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/version-history/{entityType}/{entityId}/{fromEntityVersion}/compare/{toEntityVersion}';
};

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionError = GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionErrors[keyof GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionErrors];

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionResponses = {
    /**
     * OK
     */
    200: EntityVersionComparisonResponseModel;
};

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionResponse = GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionResponses[keyof GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionResponses];

export type GetVersionHistorySupportedTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/version-history/supported-types';
};

export type GetVersionHistorySupportedTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetVersionHistorySupportedTypesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetVersionHistorySupportedTypesResponse = GetVersionHistorySupportedTypesResponses[keyof GetVersionHistorySupportedTypesResponses];

export type GetWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/workspaces';
};

export type GetWorkspacesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetWorkspacesResponses = {
    /**
     * OK
     */
    200: PagedWorkspaceItemResponseModel;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type PostWorkspacesData = {
    body?: CreateWorkspaceRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces';
};

export type PostWorkspacesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostWorkspacesError = PostWorkspacesErrors[keyof PostWorkspacesErrors];

export type PostWorkspacesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type DeleteWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteWorkspacesByIdError = DeleteWorkspacesByIdErrors[keyof DeleteWorkspacesByIdErrors];

export type DeleteWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type GetWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetWorkspacesByIdError = GetWorkspacesByIdErrors[keyof GetWorkspacesByIdErrors];

export type GetWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: WorkspaceResponseModel;
};

export type GetWorkspacesByIdResponse = GetWorkspacesByIdResponses[keyof GetWorkspacesByIdResponses];

export type PutWorkspacesByIdData = {
    body?: UpdateWorkspaceRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type PutWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutWorkspacesByIdError = PutWorkspacesByIdErrors[keyof PutWorkspacesByIdErrors];

export type PutWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkspacesByIdGroupsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        parentGroupId?: string;
    };
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups';
};

export type GetWorkspacesByIdGroupsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetWorkspacesByIdGroupsResponses = {
    /**
     * OK
     */
    200: Array<WorkspaceGroupResponseModel>;
};

export type GetWorkspacesByIdGroupsResponse = GetWorkspacesByIdGroupsResponses[keyof GetWorkspacesByIdGroupsResponses];

export type PostWorkspacesByIdGroupsData = {
    body?: CreateWorkspaceGroupRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups';
};

export type PostWorkspacesByIdGroupsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostWorkspacesByIdGroupsError = PostWorkspacesByIdGroupsErrors[keyof PostWorkspacesByIdGroupsErrors];

export type PostWorkspacesByIdGroupsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteWorkspacesByIdGroupsByGroupIdData = {
    body?: never;
    path: {
        id: string;
        groupId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups/{groupId}';
};

export type DeleteWorkspacesByIdGroupsByGroupIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteWorkspacesByIdGroupsByGroupIdError = DeleteWorkspacesByIdGroupsByGroupIdErrors[keyof DeleteWorkspacesByIdGroupsByGroupIdErrors];

export type DeleteWorkspacesByIdGroupsByGroupIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkspacesByIdGroupsByGroupIdData = {
    body?: never;
    path: {
        id: string;
        groupId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups/{groupId}';
};

export type GetWorkspacesByIdGroupsByGroupIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetWorkspacesByIdGroupsByGroupIdError = GetWorkspacesByIdGroupsByGroupIdErrors[keyof GetWorkspacesByIdGroupsByGroupIdErrors];

export type GetWorkspacesByIdGroupsByGroupIdResponses = {
    /**
     * OK
     */
    200: WorkspaceGroupResponseModel;
};

export type GetWorkspacesByIdGroupsByGroupIdResponse = GetWorkspacesByIdGroupsByGroupIdResponses[keyof GetWorkspacesByIdGroupsByGroupIdResponses];

export type PutWorkspacesByIdGroupsByGroupIdData = {
    body?: UpdateWorkspaceGroupRequestModel;
    path: {
        id: string;
        groupId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups/{groupId}';
};

export type PutWorkspacesByIdGroupsByGroupIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutWorkspacesByIdGroupsByGroupIdError = PutWorkspacesByIdGroupsByGroupIdErrors[keyof PutWorkspacesByIdGroupsByGroupIdErrors];

export type PutWorkspacesByIdGroupsByGroupIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
