// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44380/' | (string & {});
};

export type ActionItemResponseModel = {
    alias: string;
    connectionTypeAlias?: null | string;
    description?: null | string;
    group?: null | string;
    hasDynamicOutputSchema: boolean;
    icon?: null | string;
    name: string;
    outputSchema?: null | {
        [key: string]: unknown;
    };
    settingsSchema?: null | EditableModelSchemaModel;
    type: string;
};

export type ApprovalDecisionRequestModel = {
    comment?: null | string;
    outcome: ApprovalOutcomeModel;
};

export type ApprovalOutcomeModel = 'Approved' | 'Rejected';

export type AutomationAncestorResponseModel = {
    entityType: string;
    hasChildren: boolean;
    id: string;
    isFolder: boolean;
    name: string;
    parentEntityType?: null | string;
    parentId?: null | string;
};

export type AutomationExportDefinitionModel = {
    alias: string;
    canvasState?: null | string;
    connections: Array<StepConnectionModel>;
    description?: null | string;
    id: string;
    name: string;
    notificationSettings?: null | AutomationNotificationSettingsModel;
    steps: Array<ExportStepModel>;
    trigger?: null | TriggerConfigurationModel;
};

export type AutomationExportModel = {
    automation: AutomationExportDefinitionModel;
    connectionReferences: Array<ConnectionReferenceModel>;
    exportedAt: string;
    exportedFrom: ExportSourceModel;
    formatVersion: string;
};

export type AutomationHealthModel = 'Healthy' | 'Degraded' | 'Disabled';

export type AutomationImportResultModel = {
    automationAlias?: null | string;
    automationId?: null | string;
    errors: Array<string>;
    success: boolean;
    warnings: Array<string>;
};

export type AutomationItemResponseModel = {
    alias: string;
    dateCreated: string;
    dateModified: string;
    description?: null | string;
    groupId?: null | string;
    health: AutomationHealthModel;
    id: string;
    name: string;
    publishedVersion?: null | number;
    status: AutomationStatusModel;
    triggerAlias?: null | string;
    version: number;
    workspaceId: string;
};

export type AutomationNotificationSettingsModel = {
    channels: Array<ChannelConfigurationModel>;
};

export type AutomationResponseModel = {
    alias: string;
    canvasState?: null | string;
    connections: Array<StepConnectionModel>;
    dateCreated: string;
    dateModified: string;
    description?: null | string;
    disabledUtc?: null | string;
    groupId?: null | string;
    health: AutomationHealthModel;
    id: string;
    name: string;
    notificationSettings?: null | AutomationNotificationSettingsModel;
    publishedVersion?: null | number;
    status: AutomationStatusModel;
    steps: Array<StepConfigurationModel>;
    trigger?: null | TriggerConfigurationModel;
    version: number;
    warningIssuedUtc?: null | string;
    workspaceId: string;
};

export type AutomationRunCountModel = {
    automationId: string;
    automationName: string;
    failCount: number;
    successCount: number;
    totalRuns: number;
};

export type AutomationRunResponseModel = {
    automationId: string;
    automationVersion: number;
    completedUtc?: null | string;
    correlationId?: null | string;
    error?: null | string;
    id: string;
    initiatedBy: string;
    startedUtc?: null | string;
    status: AutomationRunStatusModel;
    stepRuns: Array<StepRunResponseModel>;
};

export type AutomationRunStatusModel = 'Pending' | 'Running' | 'Completed' | 'Failed' | 'Suspended' | 'Cancelled';

export type AutomationStatusModel = 'Draft' | 'Published' | 'Unpublished';

export type ChannelConfigurationModel = {
    channelAlias: string;
    isEnabled: boolean;
    notifyOn: NotifyOnModel;
    settings: {
        [key: string]: unknown;
    };
};

export type ConditionGroupModel = {
    conditions: Array<ConditionModel>;
};

export type ConditionModel = {
    leftOperand: string;
    operator: ConditionOperatorModel;
    rightOperand: string;
};

export type ConditionOperatorModel = 'Equals' | 'NotEquals' | 'Contains' | 'NotContains' | 'StartsWith' | 'EndsWith' | 'GreaterThan' | 'LessThan' | 'GreaterThanOrEquals' | 'LessThanOrEquals' | 'IsEmpty' | 'IsNotEmpty';

export type ConditionSetModel = {
    groups: Array<ConditionGroupModel>;
};

export type ConnectionItemResponseModel = {
    alias: string;
    dateCreated: string;
    dateModified: string;
    id: string;
    name: string;
    type: string;
    version: number;
};

export type ConnectionReferenceModel = {
    alias: string;
    name: string;
    type: string;
};

export type ConnectionResponseModel = {
    alias: string;
    dateCreated: string;
    dateModified: string;
    id: string;
    name: string;
    settings: {
        [key: string]: unknown;
    };
    type: string;
    version: number;
};

export type ConnectionTypeItemResponseModel = {
    alias: string;
    description?: null | string;
    group?: null | string;
    icon?: null | string;
    name: string;
    settingsSchema?: null | EditableModelSchemaModel;
};

export type ConnectionValidationResponseModel = {
    details: Array<string>;
    message?: null | string;
    status: ConnectionValidationStatusModel;
};

export type ConnectionValidationStatusModel = 'Success' | 'Warning' | 'Failure';

export type ControlFlowItemResponseModel = {
    alias: string;
    connectionTypeAlias?: null | string;
    description?: null | string;
    group?: null | string;
    hasDynamicOutputSchema: boolean;
    icon?: null | string;
    name: string;
    outputSchema?: null | {
        [key: string]: unknown;
    };
    settingsSchema?: null | EditableModelSchemaModel;
    type: string;
};

export type CreateAutomationRequestModel = {
    alias: string;
    canvasState?: null | string;
    connections: Array<StepConnectionModel>;
    description?: null | string;
    groupId?: null | string;
    name: string;
    notificationSettings?: null | AutomationNotificationSettingsModel;
    steps: Array<StepConfigurationModel>;
    trigger?: null | TriggerConfigurationModel;
    workspaceId: string;
};

export type CreateConnectionRequestModel = {
    alias: string;
    name: string;
    settings: {
        [key: string]: unknown;
    };
    type: string;
};

export type CreateWorkspaceGroupRequestModel = {
    name: string;
    parentId?: null | string;
};

export type CreateWorkspaceRequestModel = {
    alias: string;
    allowedConnections: Array<string>;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
};

export type EditableModelFieldDescriptorModel = {
    defaultValue?: unknown;
    description?: null | string;
    editorConfig?: null | string;
    editorUiAlias?: null | string;
    group?: null | string;
    isRequired: boolean;
    isSensitive: boolean;
    key: string;
    label: string;
    sortOrder: number;
    supportsBindings: boolean;
};

export type EditableModelSchemaModel = {
    fields: Array<EditableModelFieldDescriptorModel>;
};

export type EntityVersionComparisonResponseModel = {
    changes: Array<ValueChangeModel>;
    fromVersion: number;
    toVersion: number;
};

export type EntityVersionHistoryResponseModel = {
    currentVersion: number;
    publishedVersion?: null | number;
    totalVersions: number;
    versions: Array<EntityVersionResponseModel>;
};

export type EntityVersionResponseModel = {
    changeDescription?: null | string;
    createdByUserId?: null | string;
    dateCreated: string;
    entityId: string;
    id: string;
    isPublished: boolean;
    version: number;
};

export type ExportSourceModel = {
    product: string;
    version: string;
};

export type ExportStepModel = {
    actionAlias: string;
    alias?: null | string;
    connectionAlias?: null | string;
    errorBehavior: StepErrorBehaviorModel;
    id: string;
    inputMappings: {
        [key: string]: string;
    };
    maxRetries?: null | number;
    name: string;
    position: StepPositionModel;
    retryInterval?: null | string;
    settings: {
        [key: string]: unknown;
    };
};

export type ImportAutomationRequestModel = {
    exportModel: AutomationExportModel;
    workspaceId: string;
};

export type NotificationChannelItemResponseModel = {
    alias: string;
    description?: null | string;
    icon?: null | string;
    name: string;
    settingsSchema?: null | EditableModelSchemaModel;
};

export type NotifyOnModel = string;

export type PagedAutomationItemResponseModel = {
    items: Array<AutomationItemResponseModel>;
    total: number;
};

export type PagedAutomationRunResponseModel = {
    items: Array<AutomationRunResponseModel>;
    total: number;
};

export type PagedConnectionItemResponseModel = {
    items: Array<ConnectionItemResponseModel>;
    total: number;
};

export type PagedWorkspaceItemResponseModel = {
    items: Array<WorkspaceItemResponseModel>;
    total: number;
};

export type PendingApprovalResponseModel = {
    automationId: string;
    automationName: string;
    prompt?: null | string;
    requestedUtc?: null | string;
    runId: string;
    stepId: string;
};

export type ProblemDetails = {
    detail?: null | string;
    instance?: null | string;
    status?: null | number;
    title?: null | string;
    type?: null | string;
};

export type ResolveOutputSchemaRequestModel = {
    settings: {
        [key: string]: unknown;
    };
};

export type RunSummaryModel = {
    byStatus: {
        [key: string]: number;
    };
    successRate: number;
    totalRuns: number;
};

export type StepConfigurationModel = {
    actionAlias: string;
    alias?: null | string;
    connectionId?: null | string;
    errorBehavior: StepErrorBehaviorModel;
    id: string;
    inputMappings: {
        [key: string]: string;
    };
    maxRetries?: null | number;
    name: string;
    position: StepPositionModel;
    retryInterval?: null | string;
    settings: {
        [key: string]: unknown;
    };
};

export type StepConnectionModel = {
    filter?: null | ConditionSetModel;
    outcome?: null | string;
    sourceHandle?: null | string;
    sourceStepId: string;
    targetHandle?: null | string;
    targetStepId: string;
};

export type StepErrorBehaviorModel = 'Retry' | 'Suspend' | 'Terminate' | 'Compensate';

export type StepPositionModel = {
    x: number;
    y: number;
};

export type StepRunResponseModel = {
    actionAlias: string;
    completedUtc?: null | string;
    durationMs?: null | number;
    error?: null | string;
    id: string;
    retryCount: number;
    startedUtc?: null | string;
    status: StepRunStatusModel;
    stepId: string;
};

export type StepRunStatusModel = 'Pending' | 'Running' | 'Completed' | 'Failed' | 'Skipped' | 'WaitingForInput' | 'Sleeping';

export type StepTypeItemResponseModel = {
    alias: string;
    connectionTypeAlias?: null | string;
    description?: null | string;
    group?: null | string;
    hasDynamicOutputSchema: boolean;
    icon?: null | string;
    name: string;
    outputSchema?: null | {
        [key: string]: unknown;
    };
    settingsSchema?: null | EditableModelSchemaModel;
    type: string;
};

export type TriggerConfigurationModel = {
    settings: {
        [key: string]: unknown;
    };
    triggerAlias: string;
};

export type TriggerItemResponseModel = {
    alias: string;
    connectionTypeAlias?: null | string;
    description?: null | string;
    group?: null | string;
    hasDynamicOutputSchema: boolean;
    icon?: null | string;
    name: string;
    outputSchema?: null | {
        [key: string]: unknown;
    };
    settingsSchema?: null | EditableModelSchemaModel;
    type: string;
};

export type UpdateAutomationRequestModel = {
    alias: string;
    canvasState?: null | string;
    connections: Array<StepConnectionModel>;
    description?: null | string;
    groupId?: null | string;
    name: string;
    notificationSettings?: null | AutomationNotificationSettingsModel;
    steps: Array<StepConfigurationModel>;
    trigger?: null | TriggerConfigurationModel;
    version: number;
};

export type UpdateConnectionRequestModel = {
    alias: string;
    name: string;
    settings: {
        [key: string]: unknown;
    };
    type: string;
    version: number;
};

export type UpdateWorkspaceGroupRequestModel = {
    name: string;
    parentId?: null | string;
};

export type UpdateWorkspaceRequestModel = {
    alias: string;
    allowedConnections: Array<string>;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
    version: number;
};

export type ValueChangeModel = {
    newValue?: null | string;
    oldValue?: null | string;
    path: string;
};

export type WebhookAuthenticatorItemResponseModel = {
    alias: string;
    description?: null | string;
    name: string;
    settingsSchema?: null | EditableModelSchemaModel;
};

export type WorkspaceGroupResponseModel = {
    dateCreated: string;
    id: string;
    name: string;
    parentId?: null | string;
    workspaceId: string;
};

export type WorkspaceItemResponseModel = {
    alias: string;
    dateCreated: string;
    dateModified: string;
    id: string;
    name: string;
    serviceAccountKey: string;
    version: number;
};

export type WorkspaceResponseModel = {
    alias: string;
    allowedConnections: Array<string>;
    dateCreated: string;
    dateModified: string;
    id: string;
    name: string;
    serviceAccountKey: string;
    userGroups: Array<string>;
    version: number;
};

export type PostApprovalsByRunIdStepsByStepIdDecisionData = {
    body: ApprovalDecisionRequestModel;
    path: {
        runId: string;
        stepId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/approvals/{runId}/steps/{stepId}/decision';
};

export type PostApprovalsByRunIdStepsByStepIdDecisionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostApprovalsByRunIdStepsByStepIdDecisionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApprovalsPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/approvals/pending';
};

export type GetApprovalsPendingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetApprovalsPendingResponses = {
    /**
     * OK
     */
    200: Array<PendingApprovalResponseModel>;
};

export type GetApprovalsPendingResponse = GetApprovalsPendingResponses[keyof GetApprovalsPendingResponses];

export type GetAutomationsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        groupId?: string;
        workspaceId?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/automations';
};

export type GetAutomationsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAutomationsResponses = {
    /**
     * OK
     */
    200: PagedAutomationItemResponseModel;
};

export type GetAutomationsResponse = GetAutomationsResponses[keyof GetAutomationsResponses];

export type PostAutomationsData = {
    body: CreateAutomationRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations';
};

export type PostAutomationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostAutomationsError = PostAutomationsErrors[keyof PostAutomationsErrors];

export type PostAutomationsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteAutomationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type DeleteAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAutomationsByIdError = DeleteAutomationsByIdErrors[keyof DeleteAutomationsByIdErrors];

export type DeleteAutomationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type GetAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdError = GetAutomationsByIdErrors[keyof GetAutomationsByIdErrors];

export type GetAutomationsByIdResponses = {
    /**
     * OK
     */
    200: AutomationResponseModel;
};

export type GetAutomationsByIdResponse = GetAutomationsByIdResponses[keyof GetAutomationsByIdResponses];

export type PutAutomationsByIdData = {
    body: UpdateAutomationRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}';
};

export type PutAutomationsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PutAutomationsByIdError = PutAutomationsByIdErrors[keyof PutAutomationsByIdErrors];

export type PutAutomationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsByIdAncestorsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/ancestors';
};

export type GetAutomationsByIdAncestorsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdAncestorsError = GetAutomationsByIdAncestorsErrors[keyof GetAutomationsByIdAncestorsErrors];

export type GetAutomationsByIdAncestorsResponses = {
    /**
     * OK
     */
    200: Array<AutomationAncestorResponseModel>;
};

export type GetAutomationsByIdAncestorsResponse = GetAutomationsByIdAncestorsResponses[keyof GetAutomationsByIdAncestorsResponses];

export type GetAutomationsByIdExportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        include?: string;
    };
    url: '/umbraco/automate/management/api/v1/automations/{id}/export';
};

export type GetAutomationsByIdExportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdExportError = GetAutomationsByIdExportErrors[keyof GetAutomationsByIdExportErrors];

export type GetAutomationsByIdExportResponses = {
    /**
     * OK
     */
    200: AutomationExportModel;
};

export type GetAutomationsByIdExportResponse = GetAutomationsByIdExportResponses[keyof GetAutomationsByIdExportResponses];

export type PutAutomationsByIdImportData = {
    body: AutomationExportModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/import';
};

export type PutAutomationsByIdImportErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutAutomationsByIdImportError = PutAutomationsByIdImportErrors[keyof PutAutomationsByIdImportErrors];

export type PutAutomationsByIdImportResponses = {
    /**
     * OK
     */
    200: AutomationImportResultModel;
};

export type PutAutomationsByIdImportResponse = PutAutomationsByIdImportResponses[keyof PutAutomationsByIdImportResponses];

export type PostAutomationsByIdPublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/publish';
};

export type PostAutomationsByIdPublishErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
};

export type PostAutomationsByIdPublishError = PostAutomationsByIdPublishErrors[keyof PostAutomationsByIdPublishErrors];

export type PostAutomationsByIdPublishResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAutomationsByIdReEnableData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/re-enable';
};

export type PostAutomationsByIdReEnableErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostAutomationsByIdReEnableError = PostAutomationsByIdReEnableErrors[keyof PostAutomationsByIdReEnableErrors];

export type PostAutomationsByIdReEnableResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsByIdRunsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/automations/{id}/runs';
};

export type GetAutomationsByIdRunsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsByIdRunsError = GetAutomationsByIdRunsErrors[keyof GetAutomationsByIdRunsErrors];

export type GetAutomationsByIdRunsResponses = {
    /**
     * OK
     */
    200: PagedAutomationRunResponseModel;
};

export type GetAutomationsByIdRunsResponse = GetAutomationsByIdRunsResponses[keyof GetAutomationsByIdRunsResponses];

export type PostAutomationsByIdTriggerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/trigger';
};

export type PostAutomationsByIdTriggerErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostAutomationsByIdTriggerError = PostAutomationsByIdTriggerErrors[keyof PostAutomationsByIdTriggerErrors];

export type PostAutomationsByIdTriggerResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PostAutomationsByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/{id}/unpublish';
};

export type PostAutomationsByIdUnpublishErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
};

export type PostAutomationsByIdUnpublishError = PostAutomationsByIdUnpublishErrors[keyof PostAutomationsByIdUnpublishErrors];

export type PostAutomationsByIdUnpublishResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAutomationsGroupsByGroupIdData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/groups/{groupId}';
};

export type GetAutomationsGroupsByGroupIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAutomationsGroupsByGroupIdError = GetAutomationsGroupsByGroupIdErrors[keyof GetAutomationsGroupsByGroupIdErrors];

export type GetAutomationsGroupsByGroupIdResponses = {
    /**
     * OK
     */
    200: WorkspaceGroupResponseModel;
};

export type GetAutomationsGroupsByGroupIdResponse = GetAutomationsGroupsByGroupIdResponses[keyof GetAutomationsGroupsByGroupIdResponses];

export type PostAutomationsImportData = {
    body: ImportAutomationRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/import';
};

export type PostAutomationsImportErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostAutomationsImportError = PostAutomationsImportErrors[keyof PostAutomationsImportErrors];

export type PostAutomationsImportResponses = {
    /**
     * Created
     */
    201: AutomationImportResultModel;
};

export type PostAutomationsImportResponse = PostAutomationsImportResponses[keyof PostAutomationsImportResponses];

export type PostAutomationsImportValidateData = {
    body: ImportAutomationRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/automations/import/validate';
};

export type PostAutomationsImportValidateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostAutomationsImportValidateError = PostAutomationsImportValidateErrors[keyof PostAutomationsImportValidateErrors];

export type PostAutomationsImportValidateResponses = {
    /**
     * OK
     */
    200: AutomationImportResultModel;
};

export type PostAutomationsImportValidateResponse = PostAutomationsImportValidateResponses[keyof PostAutomationsImportValidateResponses];

export type GetCatalogueActionsData = {
    body?: never;
    path?: never;
    query?: {
        workspaceId?: string;
    };
    url: '/umbraco/automate/management/api/v1/catalogue/actions';
};

export type GetCatalogueActionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetCatalogueActionsResponses = {
    /**
     * OK
     */
    200: Array<ActionItemResponseModel>;
};

export type GetCatalogueActionsResponse = GetCatalogueActionsResponses[keyof GetCatalogueActionsResponses];

export type GetCatalogueConnectionTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/connection-types';
};

export type GetCatalogueConnectionTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueConnectionTypesResponses = {
    /**
     * OK
     */
    200: Array<ConnectionTypeItemResponseModel>;
};

export type GetCatalogueConnectionTypesResponse = GetCatalogueConnectionTypesResponses[keyof GetCatalogueConnectionTypesResponses];

export type GetCatalogueControlFlowsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/control-flows';
};

export type GetCatalogueControlFlowsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueControlFlowsResponses = {
    /**
     * OK
     */
    200: Array<ControlFlowItemResponseModel>;
};

export type GetCatalogueControlFlowsResponse = GetCatalogueControlFlowsResponses[keyof GetCatalogueControlFlowsResponses];

export type GetCatalogueNotificationChannelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/notification-channels';
};

export type GetCatalogueNotificationChannelsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueNotificationChannelsResponses = {
    /**
     * OK
     */
    200: Array<NotificationChannelItemResponseModel>;
};

export type GetCatalogueNotificationChannelsResponse = GetCatalogueNotificationChannelsResponses[keyof GetCatalogueNotificationChannelsResponses];

export type GetCatalogueStepTypesData = {
    body?: never;
    path?: never;
    query?: {
        type?: string;
    };
    url: '/umbraco/automate/management/api/v1/catalogue/step-types';
};

export type GetCatalogueStepTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueStepTypesResponses = {
    /**
     * OK
     */
    200: Array<StepTypeItemResponseModel>;
};

export type GetCatalogueStepTypesResponse = GetCatalogueStepTypesResponses[keyof GetCatalogueStepTypesResponses];

export type PostCatalogueStepTypesByAliasOutputSchemaData = {
    body: ResolveOutputSchemaRequestModel;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/step-types/{alias}/output-schema';
};

export type PostCatalogueStepTypesByAliasOutputSchemaErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostCatalogueStepTypesByAliasOutputSchemaError = PostCatalogueStepTypesByAliasOutputSchemaErrors[keyof PostCatalogueStepTypesByAliasOutputSchemaErrors];

export type PostCatalogueStepTypesByAliasOutputSchemaResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostCatalogueStepTypesByAliasOutputSchemaResponse = PostCatalogueStepTypesByAliasOutputSchemaResponses[keyof PostCatalogueStepTypesByAliasOutputSchemaResponses];

export type GetCatalogueTriggersData = {
    body?: never;
    path?: never;
    query?: {
        workspaceId?: string;
    };
    url: '/umbraco/automate/management/api/v1/catalogue/triggers';
};

export type GetCatalogueTriggersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetCatalogueTriggersResponses = {
    /**
     * OK
     */
    200: Array<TriggerItemResponseModel>;
};

export type GetCatalogueTriggersResponse = GetCatalogueTriggersResponses[keyof GetCatalogueTriggersResponses];

export type GetCatalogueWebhookAuthenticatorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/catalogue/webhook-authenticators';
};

export type GetCatalogueWebhookAuthenticatorsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCatalogueWebhookAuthenticatorsResponses = {
    /**
     * OK
     */
    200: Array<WebhookAuthenticatorItemResponseModel>;
};

export type GetCatalogueWebhookAuthenticatorsResponse = GetCatalogueWebhookAuthenticatorsResponses[keyof GetCatalogueWebhookAuthenticatorsResponses];

export type GetConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/connections';
};

export type GetConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConnectionsResponses = {
    /**
     * OK
     */
    200: PagedConnectionItemResponseModel;
};

export type GetConnectionsResponse = GetConnectionsResponses[keyof GetConnectionsResponses];

export type PostConnectionsData = {
    body: CreateConnectionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections';
};

export type PostConnectionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostConnectionsError = PostConnectionsErrors[keyof PostConnectionsErrors];

export type PostConnectionsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteConnectionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type DeleteConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteConnectionsByIdError = DeleteConnectionsByIdErrors[keyof DeleteConnectionsByIdErrors];

export type DeleteConnectionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type GetConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConnectionsByIdError = GetConnectionsByIdErrors[keyof GetConnectionsByIdErrors];

export type GetConnectionsByIdResponses = {
    /**
     * OK
     */
    200: ConnectionResponseModel;
};

export type GetConnectionsByIdResponse = GetConnectionsByIdResponses[keyof GetConnectionsByIdResponses];

export type PutConnectionsByIdData = {
    body: UpdateConnectionRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}';
};

export type PutConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PutConnectionsByIdError = PutConnectionsByIdErrors[keyof PutConnectionsByIdErrors];

export type PutConnectionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostConnectionsByIdTestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/connections/{id}/test';
};

export type PostConnectionsByIdTestErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostConnectionsByIdTestError = PostConnectionsByIdTestErrors[keyof PostConnectionsByIdTestErrors];

export type PostConnectionsByIdTestResponses = {
    /**
     * OK
     */
    200: ConnectionValidationResponseModel;
};

export type PostConnectionsByIdTestResponse = PostConnectionsByIdTestResponses[keyof PostConnectionsByIdTestResponses];

export type GetMetricsData = {
    body?: never;
    path?: never;
    query?: {
        workspaceId?: string;
        from?: string;
        to?: string;
    };
    url: '/umbraco/automate/management/api/v1/metrics';
};

export type GetMetricsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetMetricsResponses = {
    /**
     * OK
     */
    200: RunSummaryModel;
};

export type GetMetricsResponse = GetMetricsResponses[keyof GetMetricsResponses];

export type GetMetricsByAutomationData = {
    body?: never;
    path?: never;
    query?: {
        workspaceId?: string;
        from?: string;
        to?: string;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/metrics/by-automation';
};

export type GetMetricsByAutomationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetMetricsByAutomationResponses = {
    /**
     * OK
     */
    200: Array<AutomationRunCountModel>;
};

export type GetMetricsByAutomationResponse = GetMetricsByAutomationResponses[keyof GetMetricsByAutomationResponses];

export type GetRunsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/runs/{id}';
};

export type GetRunsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetRunsByIdError = GetRunsByIdErrors[keyof GetRunsByIdErrors];

export type GetRunsByIdResponses = {
    /**
     * OK
     */
    200: AutomationRunResponseModel;
};

export type GetRunsByIdResponse = GetRunsByIdResponses[keyof GetRunsByIdResponses];

export type PostRunsByIdReplayData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/runs/{id}/replay';
};

export type PostRunsByIdReplayErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostRunsByIdReplayError = PostRunsByIdReplayErrors[keyof PostRunsByIdReplayErrors];

export type PostRunsByIdReplayResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PostRunsByIdResumeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/runs/{id}/resume';
};

export type PostRunsByIdResumeErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostRunsByIdResumeError = PostRunsByIdResumeErrors[keyof PostRunsByIdResumeErrors];

export type PostRunsByIdResumeResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PostRunsByIdSuspendData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/runs/{id}/suspend';
};

export type PostRunsByIdSuspendErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostRunsByIdSuspendError = PostRunsByIdSuspendErrors[keyof PostRunsByIdSuspendErrors];

export type PostRunsByIdSuspendResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PostRunsByIdTerminateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/runs/{id}/terminate';
};

export type PostRunsByIdTerminateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostRunsByIdTerminateError = PostRunsByIdTerminateErrors[keyof PostRunsByIdTerminateErrors];

export type PostRunsByIdTerminateResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type GetVersionHistoryByEntityTypeByEntityIdData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/version-history/{entityType}/{entityId}';
};

export type GetVersionHistoryByEntityTypeByEntityIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionHistoryByEntityTypeByEntityIdError = GetVersionHistoryByEntityTypeByEntityIdErrors[keyof GetVersionHistoryByEntityTypeByEntityIdErrors];

export type GetVersionHistoryByEntityTypeByEntityIdResponses = {
    /**
     * OK
     */
    200: EntityVersionHistoryResponseModel;
};

export type GetVersionHistoryByEntityTypeByEntityIdResponse = GetVersionHistoryByEntityTypeByEntityIdResponses[keyof GetVersionHistoryByEntityTypeByEntityIdResponses];

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        entityVersion: number;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/version-history/{entityType}/{entityId}/{entityVersion}';
};

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionError = GetVersionHistoryByEntityTypeByEntityIdByEntityVersionErrors[keyof GetVersionHistoryByEntityTypeByEntityIdByEntityVersionErrors];

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionResponses = {
    /**
     * OK
     */
    200: EntityVersionResponseModel;
};

export type GetVersionHistoryByEntityTypeByEntityIdByEntityVersionResponse = GetVersionHistoryByEntityTypeByEntityIdByEntityVersionResponses[keyof GetVersionHistoryByEntityTypeByEntityIdByEntityVersionResponses];

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        entityVersion: number;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/version-history/{entityType}/{entityId}/{entityVersion}/rollback';
};

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackError = PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackErrors[keyof PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackErrors];

export type PostVersionHistoryByEntityTypeByEntityIdByEntityVersionRollbackResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        fromEntityVersion: number;
        toEntityVersion: number;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/version-history/{entityType}/{entityId}/{fromEntityVersion}/compare/{toEntityVersion}';
};

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionError = GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionErrors[keyof GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionErrors];

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionResponses = {
    /**
     * OK
     */
    200: EntityVersionComparisonResponseModel;
};

export type GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionResponse = GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionResponses[keyof GetVersionHistoryByEntityTypeByEntityIdByFromEntityVersionCompareByToEntityVersionResponses];

export type GetVersionHistorySupportedTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/version-history/supported-types';
};

export type GetVersionHistorySupportedTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetVersionHistorySupportedTypesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetVersionHistorySupportedTypesResponse = GetVersionHistorySupportedTypesResponses[keyof GetVersionHistorySupportedTypesResponses];

export type GetWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/automate/management/api/v1/workspaces';
};

export type GetWorkspacesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetWorkspacesResponses = {
    /**
     * OK
     */
    200: PagedWorkspaceItemResponseModel;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type PostWorkspacesData = {
    body: CreateWorkspaceRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces';
};

export type PostWorkspacesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostWorkspacesError = PostWorkspacesErrors[keyof PostWorkspacesErrors];

export type PostWorkspacesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type DeleteWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type DeleteWorkspacesByIdError = DeleteWorkspacesByIdErrors[keyof DeleteWorkspacesByIdErrors];

export type DeleteWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type GetWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetWorkspacesByIdError = GetWorkspacesByIdErrors[keyof GetWorkspacesByIdErrors];

export type GetWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: WorkspaceResponseModel;
};

export type GetWorkspacesByIdResponse = GetWorkspacesByIdResponses[keyof GetWorkspacesByIdResponses];

export type PutWorkspacesByIdData = {
    body: UpdateWorkspaceRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}';
};

export type PutWorkspacesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PutWorkspacesByIdError = PutWorkspacesByIdErrors[keyof PutWorkspacesByIdErrors];

export type PutWorkspacesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkspacesByIdGroupsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        parentGroupId?: string;
    };
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups';
};

export type GetWorkspacesByIdGroupsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetWorkspacesByIdGroupsResponses = {
    /**
     * OK
     */
    200: Array<WorkspaceGroupResponseModel>;
};

export type GetWorkspacesByIdGroupsResponse = GetWorkspacesByIdGroupsResponses[keyof GetWorkspacesByIdGroupsResponses];

export type PostWorkspacesByIdGroupsData = {
    body: CreateWorkspaceGroupRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups';
};

export type PostWorkspacesByIdGroupsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostWorkspacesByIdGroupsError = PostWorkspacesByIdGroupsErrors[keyof PostWorkspacesByIdGroupsErrors];

export type PostWorkspacesByIdGroupsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteWorkspacesByIdGroupsByGroupIdData = {
    body?: never;
    path: {
        id: string;
        groupId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups/{groupId}';
};

export type DeleteWorkspacesByIdGroupsByGroupIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteWorkspacesByIdGroupsByGroupIdError = DeleteWorkspacesByIdGroupsByGroupIdErrors[keyof DeleteWorkspacesByIdGroupsByGroupIdErrors];

export type DeleteWorkspacesByIdGroupsByGroupIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetWorkspacesByIdGroupsByGroupIdData = {
    body?: never;
    path: {
        id: string;
        groupId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups/{groupId}';
};

export type GetWorkspacesByIdGroupsByGroupIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetWorkspacesByIdGroupsByGroupIdError = GetWorkspacesByIdGroupsByGroupIdErrors[keyof GetWorkspacesByIdGroupsByGroupIdErrors];

export type GetWorkspacesByIdGroupsByGroupIdResponses = {
    /**
     * OK
     */
    200: WorkspaceGroupResponseModel;
};

export type GetWorkspacesByIdGroupsByGroupIdResponse = GetWorkspacesByIdGroupsByGroupIdResponses[keyof GetWorkspacesByIdGroupsByGroupIdResponses];

export type PutWorkspacesByIdGroupsByGroupIdData = {
    body: UpdateWorkspaceGroupRequestModel;
    path: {
        id: string;
        groupId: string;
    };
    query?: never;
    url: '/umbraco/automate/management/api/v1/workspaces/{id}/groups/{groupId}';
};

export type PutWorkspacesByIdGroupsByGroupIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutWorkspacesByIdGroupsByGroupIdError = PutWorkspacesByIdGroupsByGroupIdErrors[keyof PutWorkspacesByIdGroupsByGroupIdErrors];

export type PutWorkspacesByIdGroupsByGroupIdResponses = {
    /**
     * OK
     */
    200: unknown;
};
