<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <Title>Umbraco Automate</Title>
        <Description>Contains static assets for Umbraco Automate</Description>
        <StaticWebAssetBasePath>App_Plugins/UmbracoAutomate</StaticWebAssetBasePath>
        <AddRazorSupportForMvc>false</AddRazorSupportForMvc>
    </PropertyGroup>

    <ItemGroup>
        <!-- Dont include the client folder as part of packaging nuget build -->
        <Content Remove="Client\**" />
        <Content Include="Client\package.json" />
        <Content Include="Client\tsconfig.json" />

        <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
        <None Include="Client\public\umbraco-package.json" Pack="false" />
    </ItemGroup>

    <Target Name="UpdatePackageManifestVersion" BeforeTargets="CoreCompile" Condition="Exists('wwwroot\umbraco-package.json') AND '$(PackageVersion)' != ''">
        <Message Text="Update umbraco-package.json files with current build version $(PackageVersion)" Importance="high" />
        <ItemGroup>
            <_PackageManifestFiles Include="wwwroot\umbraco-package.json" />
        </ItemGroup>
        <JsonPathUpdateValue JsonFile="%(_PackageManifestFiles.FullPath)" Path="$.version" Value="&quot;$(PackageVersion)&quot;" />
    </Target>

</Project>
