<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Umbraco Forms Automate</Title>
        <Description>Umbraco Forms triggers and actions for Umbraco Automate</Description>
    </PropertyGroup>

    <PropertyGroup>
        <UseProjectReferences Condition="'$(UseProjectReferences)' == ''">true</UseProjectReferences>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\..\..\Umbraco.Automate\src\Umbraco.Automate.Core\Umbraco.Automate.Core.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
        <PackageReference Include="Umbraco.Automate.Core" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Umbraco.Forms.Core" />
    </ItemGroup>

</Project>
