<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <Title>Umbraco Automate OpenIddict</Title>
      <Description>OAuth connection support for Umbraco Automate using OpenIddict Client WebIntegration</Description>
      <PackageReadmeFile>docs\README.md</PackageReadmeFile>
      <IncludeBuildOutput>false</IncludeBuildOutput>
      <IncludeSymbols>false</IncludeSymbols>
      <IncludeReferencedProjects>true</IncludeReferencedProjects>
    </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="docs" />
  </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Umbraco.Automate.OpenIddict.Core\Umbraco.Automate.OpenIddict.Core.csproj" />
        <ProjectReference Include="..\Umbraco.Automate.OpenIddict.Persistence.SqlServer\Umbraco.Automate.OpenIddict.Persistence.SqlServer.csproj" />
        <ProjectReference Include="..\Umbraco.Automate.OpenIddict.Persistence.Sqlite\Umbraco.Automate.OpenIddict.Persistence.Sqlite.csproj" />
    </ItemGroup>

</Project>
